baseURL: ''
languageCode: 'en-us'
title: 'ADITI NAIR'
theme: "hugo-PaperMod"

menu:
    main:
      - identifier: About
        name: About
        url: /about/
        weight: 10
    



params:
    homeInfoParams:
        Title: Hello World!
        Content: Welcome to my Portfolio! 



    socialIcons: # optional
    - name: linkedin
      url: "<https://www.linkedin.com/in/aditinair6>" 
    - name: github
      url: "<https://github.com/addynair/>"
    - name: twitter
      url: "<https://twitter.com/aditinair06>" 
    - name: telegram
      url: "<t.me/Addynair>" 
