baseURL = ''
languageCode = 'en-us'
title = 'Aditi Nair'
theme = "hugo-theme-m10c"

[params]
  author = 'Aditi Nair'
  description = 'A first year Btech student in Amrita Vishwa vidyapeetham'
 
    
[[params.social]]
    icon = "github"
    name = "My Github"
    url = "https://github.com/addynair"

      

[[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/gohugoio"

[[params.social]]
    icon = "mail"
    name = "Gmail"
    url = "mailto:addynair6@gmail.com"

[[params.social]]
    icon = "linkedin"
    name = "Gmail"
    url = "https://www.linkedin.com/in/aditinair6"


